### PR TITLE
SIKKA-4578[COMPLETED] failed to build lib

### PR DESCRIPTION
**Pull request by RayanMasri**
Failed to `npm run build-lib` , although added new back-to-top features

### CODE REVIEW

**Comment by zaaakher** [comment]
Task linked: [SIKKA-4578 make BackToTop work on different divs (cards)](https://app.clickup.com/t/613523/SIKKA-4578)

**Comment by zaaakher** [comment]
Ok, I'll check it out and pull your PR locally and push along with my upcoming push inshallah.

@RayanMasri could you share the error you see when you run `npm run build-lib` ? 

Also try deleting `package-lock` and `yarn.lock` and maybe even `node_modules` and then try building the library again

**Comment by RayanMasri** [comment]
```
[!] Error: Cannot find module '@rollup/plugin-babel'
Require stack:
- C:\Users\MrRya\OneDrive\Desktop\main\js\sikka\Hawa Contibution\arrow-carousel\rollup.config.js
- C:\Users\MrRya\OneDrive\Desktop\main\js\sikka\Hawa Contibution\arrow-carousel\node_modules\rollup\dist\shared\loadConfigFile.js
- C:\Users\MrRya\OneDrive\Desktop\main\js\sikka\Hawa Contibution\arrow-carousel\node_modules\rollup\dist\bin\rollup
Error: Cannot find module '@rollup/plugin-babel'
Require stack:
- C:\Users\MrRya\OneDrive\Desktop\main\js\sikka\Hawa Contibution\arrow-carousel\rollup.config.js
- C:\Users\MrRya\OneDrive\Desktop\main\js\sikka\Hawa Contibution\arrow-carousel\node_modules\rollup\dist\shared\loadConfigFile.js
- C:\Users\MrRya\OneDrive\Desktop\main\js\sikka\Hawa Contibution\arrow-carousel\node_modules\rollup\dist\bin\rollup
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\MrRya\OneDrive\Desktop\main\js\sikka\Hawa Contibution\arrow-carousel\rollup.config.js:7:19)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.require.extensions.<computed> [as .js] (C:\Users\MrRya\OneDrive\Desktop\main\js\sikka\Hawa Contibution\arrow-carousel\node_modules\rollup\dist\shared\loadConfigFile.js:621:20)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Comment by zaaakher** [comment]
Yes I added that plugin in one of the recent commits to fix some deprecation warnings when running the build library command.

It think it will work if you run `npm i` to install the packages I added recently

**Pull request merged**
